const menu = [
  {
    id: 123,
    title: '',
    category: 'Mercedes Benz',
    price: 15.99,
    img: './one.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 233,
    title: 'diner double',
    category: 'Toyota',
    price: 13.99,
    img: './scecond.jpeg',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 211,
    title: 'diner double',
    category: 'Toyota',
    price: 13.99,
    img: './ten.jpeg',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 31,
    title: 'godzilla milkshake',
    category: 'Audi',
    price: 6.99,
    img: './third.jpeg',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4444,
    title: 'country delight',
    category: 'Peugeot',
    price: 20.99,
    img: './four.jpeg',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'Peugeot',
    price: 22.99,
    img: './five.jpeg',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 600,
    title: 'oreo dream',
    category: 'Toyota',
    price: 18.99,
    img: './six.jpeg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 700,
    title: 'bacon overflow',
    category: 'Audi',
    price: 8.99,
    img: './seven.jpeg',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 800,
    title: 'american classic',
    category: 'Mercedes Benz',
    price: 12.99,
    img: './eight.jpeg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 900,
    title: 'quarantine buddy',
    category: 'Mercedes Benz',
    price: 16.99,
    img: './nine.jpeg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default menu;
